# site settings
title: Lanzamientos Nintendo Switch 
subtitle: Octubre 2017
email: dannyzam.bit@gmail.com
description: Lista de juegos de Nintendo Switch<br /> durante el mes de Octubre.
baseurl: "/NSW-Upcoming-Games" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
country: México

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 20

# social settings
500px_url:
facebook_url:
github_url:
instagram_url: https://instagram.com
twitter_url: https://twitter.com/nindose

# build settings
markdown: kramdown
theme: Forty

sass:
  style: compressed
